version: '3.4'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=Epicman12
      - MYSQL_DATABASE=comms
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    image: server
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=Epicman12
      - DB_NAME=comms
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db:

    
